# Generated by Django 5.0.2 on 2024-03-09 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Birthday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('birth_date', models.DateField()),
                ('image', models.ImageField(blank=True, default='/birthday_images/defImg.webp', upload_to='birthday_images/')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
            ],
        ),
    ]
